# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envault < Formula
  desc "AI-era .env encryption CLI — never plaintext on disk"
  homepage "https://github.com/frahet/envault"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frahet/envault/releases/download/v0.3.0/envault_0.3.0_darwin_amd64.tar.gz"
      sha256 "bd4a1f34c5d567754b4454da063c40031643997dbcce0f31b3bbb86a967d3286"

      define_method(:install) do
        bin.install "envault"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frahet/envault/releases/download/v0.3.0/envault_0.3.0_darwin_arm64.tar.gz"
      sha256 "b107e1735f1d286a60f9cb7b7d6260d54fd5203e3b537c9038867bce584a3a3e"

      define_method(:install) do
        bin.install "envault"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frahet/envault/releases/download/v0.3.0/envault_0.3.0_linux_amd64.tar.gz"
      sha256 "58688a4e15e9d8e396f4ad3a872fd18d9b43ef255b0d5a6c7272efeafd3b4f34"
      define_method(:install) do
        bin.install "envault"
      end
    end
  end

  test do
    system "#{bin}/envault", "version"
  end
end
